@extends('layouts.header')

@section('content')

<!-- <div class="right_col booking" role="main"> -->
<!-- <div class="container-fluid"> -->
	<div class="col-md-12 col-sm-12">
	<h2 class="table-title">Data Server</h2>
	@if(session()->has('message'))
	<div class="alert alert-success">
			{{ session()->get('message') }}
	</div>
    @endif
    
    <!-- Action button templates -->
    <div id="viewBtnTemplate" style="display: none;">
        <a href="">
        <button style="padding: 3px 8px" type="button" class="btn btn-primary" title="Detail Domain">
            <i class="fa fa-search"></i>
        </button>
        </a>
    </div>
    <div id="editBtnTemplate" style="display: none;">
        <a href="">
        <button id="editBtn" style="padding: 3px 8px" type="button" class="btn btn-warning" title="Edit Domain">
            <i class="fa fa-pencil"></i>
        </button>
        </a> 
    </div>
    <div id="delBtnTemplate" style="display: none;">
        <form action="{{ route('domain.delete',['id'=>0]) }}" method="post" class="d-inline">    
            @csrf
            <button style="padding: 3px 8px;" type="submit" class="btn btn-danger" onclick="return confirm('Apakah anda yakin untuk menghapus Domain?')" title="Hapus Domain">
                <i class="fa fa-trash-o"></i>
            </button>
        </form>
    </div>
    
	<table id="serverTable" 
        class="table table-bordered table-striped table-bordered table-hover dataTable"
		data-length="{{ $length }}"
		data-ajaxurl="{{ route('server.data') }}" 
	>
		<thead class="thead-custom-blue">
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Nama Server</th>
				<th scope="col">Tipe Server</th>
                <th scope="col">Tanggal Aktif</th>
                <th scope="col">Lokasi Server</th>
                <th scope="col">No Rack</th>
                <th scope="col">Aksi</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($servers as $server)
			<tr>
				<td>{{ $server->id }}</td>
				<td>{{ $server->nama_server }}</td>
                <td>{{ $server->type_server }}</td>
                <td>{{ $server->tgl_aktif }}</td>
				<td>{{ $server->lokasi_server }}</td>
                <td>{{ $server->no_rack }}</td>
                <td></td>
			</tr>
			@endforeach
        </tbody>
        <!-- <tfoot>
			<tr>
				<th></th>
				<th><input type="text" placeholder="Search Nama"></th>
				<th><input type="text" placeholder="Search Nama"></th> -->
					<!-- <select id="searchTypeSelect">
						<option value="">Semua</option> -->
						<!-- The rest of the options are generated by js -->
					<!-- </select> -->
				<!-- </th>
				<th></th>
				<th></th>
			</tr>
		</tfoot> -->
	</table>
	</div>
<!-- </div> -->
<!-- </div> -->
@endsection

@section('scripts')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.css" defer/>
<script src="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.js" defer></script>
<script src="{{asset('js/util/datatablesPlugin.js') }}" defer></script>
<script src="{{asset('js/server/view.js') }}" defer></script>
@endsection